package vela

import (
	velacommon "github.com/oam-dev/kubevela/apis/core.oam.dev/common"
	"k8s.io/apimachinery/pkg/runtime"
)

type Component interface {
	// GetName ...
	GetName() string
	// SetName ...
	SetName(name string)
	// GetType ...
	GetType() string
	// SetType ...
	SetType(_type string)
	// Properties ...
	Properties
	// GetTraits ...
	GetTraits() []Trait
	// SetTraits ...
	SetTraits(traits []Trait)
	// FromVelaComponent ...
	FromVelaComponent(component *velacommon.ApplicationComponent) error
	// ToVelaComponent ...
	ToVelaComponent() (*velacommon.ApplicationComponent, error)
}

type Properties interface {
	// GetParameters ...
	GetParameters() *runtime.RawExtension
	// SetParameters ...
	SetParameters(parameters *runtime.RawExtension) error
}

type Trait interface {
	Properties
	// GetType ...
	GetType() string
	// SetType ...
	SetType(_type string)
	// FromVelaTrait ...
	FromVelaTrait(trait *velacommon.ApplicationTrait) error
	// ToVelaTrait ...
	ToVelaTrait() (*velacommon.ApplicationTrait, error)
}
