package vela

import "k8s.io/apimachinery/pkg/runtime"

type Component interface {
	// GetName ...
	GetName() string
	// SetName ...
	SetName(name string)
	// GetType ...
	GetType() string
	// SetType ...
	SetType(_type string)
	// GetProperties ...
	GetProperties() Properties
	// SetProperties ...
	SetProperties(properties Properties)
	// GetTraits ...
	GetTraits() []Trait
	// SetTraits ...
	SetTraits(traits []Trait)
}

type Properties interface {
	// GetParameters ...
	GetParameters() *runtime.RawExtension
}

type Trait interface {
	// GetType ...
	GetType() string
	// SetType ...
	SetType(_type string)
	// GetProperties ...
	GetProperties() Properties
	// SetProperties ...
	SetProperties(properties Properties)
}
