FROM debian:11
RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free\ndeb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free\ndeb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free\ndeb http://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free\n" > /etc/apt/sources.list
ENV ANSIBLE_VERSION=2.10.8
RUN apt-get update && apt-get install ansible=$(eval echo $(apt-cache madison ansible | grep $ANSIBLE_VERSION |head -n 1 | awk -F'|' '{print $2}')) sshpass  -y
