# permissions for end users to view nodemetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodemetrics-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuiler-demo
    app.kubernetes.io/part-of: kubebuiler-demo
    app.kubernetes.io/managed-by: kustomize
  name: nodemetrics-viewer-role
rules:
- apiGroups:
  - metrics.k8s
  resources:
  - nodemetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s
  resources:
  - nodemetrics/status
  verbs:
  - get
