# permissions for end users to view mydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: mydeployment-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - mydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - mydeployments/status
  verbs:
  - get
