---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - mydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - mydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - demo.my.domain
  resources:
  - mydeployments/status
  verbs:
  - get
  - patch
  - update
