apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ansible-binding
subjects:
  - kind: ServiceAccount
    name: ansible-sa
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ansible
  apiGroup: rbac.authorization.k8s.io
