# ansible cfg
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-cfg
  namespace: {{ .Release.Namespace }}
data:
  ansible.cfg: |-
    {{ .Values.ansibleCfg | nindent 4 }}
  hosts: |-
    {{ .Values.ansibleHosts | nindent 4 }}
---
# ansible playbooks
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-playbooks
  namespace: {{ .Release.Namespace }}
data:
  playbook.yaml: |-
    {{ .Values.ansiblePlaybooks.playbook | nindent 4}}
