# ssh cfgs
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  name: ansible-ssh-auth
  namespace: {{ .Release.Namespace }}
data:
  ssh-privatekey: {{ .Values.ssh.privateKey | b64enc  }}
  known_hosts: {{ .Values.ssh.knownHosts | b64enc}}

