# ssh cfgs
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ansible-ssh-auth
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.ssh.privateKey}}
  ssh-privatekey: {{ .Values.ssh.privateKey | b64enc  }}
  {{end}}
  {{- with .Values.ssh.knownHosts}}
  known_hosts: {{ .Values.ssh.knownHosts | b64enc }}
  {{ end }}

